---
all:
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    common_var: 1
    var_under_test:
      - yes
      - no

  hosts:
    my_host1:
      other_var_under_test:
        - "{{ common_var + 1 }}"
    my_host2:
      other_var_under_test:
        nested: "{{ common_var + 2 }}"
    my_host3:
